events {
  worker_connections  1024;  ## Default: 1024
}
http {
    upstream apps {
        #ip_hash;
        #least_conn;
        server app1:8081; 
        #weight=3;
        server app2:8082;
    }
    server {
        listen 80;
        server_name localhost;
        location / {
            root   html;
            index  index.html index.htm;
            proxy_pass http://apps;
        }
    }
}